export const SET_PHOTO = 'SET_PHOTO';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const TOGGLE_IS_PHOTO_DETAIL_STATUS = 'TOGGLE_IS_PHOTO_DETAIL_STATUS';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';